#
# Puppet code validation workflow
#
name: "Validate Puppet code"

concurrency: 
  group: PDK_validate_wkf_group

on:
  workflow_dispatch:

  push:
    paths:
      - '**.json'
      - '**.rb'
      - '**.pp'
      - '**.erb'
      - '**.epp'
      - '**.yml'
      
  pull_request:
    branches: [ "main", "release/**" ]
    paths:
      - '**.json'
      - '**.rb'
      - '**.pp'
      - '**.erb'
      - '**.epp'
      - '**.yml'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate
        uses: mysociety/action-pdk@master
        with:
          action: 'validate'

      - name: Run Unit Tests
        uses: mysociety/action-pdk@master
        with:
          action: 'test unit'